/**
 * render.mjs — Markdown to HTML for this site.
 *
 * Three things here are site-specific rather than generic Markdown:
 *
 *  1. Stable heading anchors. A Chinese heading slugifies to nothing usable, so
 *     ids are positional (`sec-1`, `sec-2`) and never derived from the text —
 *     which also means editing a heading's wording cannot break a link
 *     someone saved.
 *  2. Section wrappers with a disclosure control, which is the whole of gwern's
 *     "semantic zoom" at the block level: a long piece can be read as headings
 *     alone, then expanded section by section.
 *  3. Footnote/sidenote and `{{ref:}}` handling, both preprocessed BEFORE
 *     marked so their bodies are themselves parsed as Markdown.
 */

import { marked } from "marked";
import { esc, plain, slugify } from "./lib.mjs";
import { replaceFootnotes, extractRefs, restoreRefs } from "./content.mjs";

/* ══════════════════════════════════════════════════════════════════════ */
/* headings & sections                                                   */
/* ══════════════════════════════════════════════════════════════════════ */

/** Collect every heading's level, text and positional id. */
function headingTokens(tokens, out = []) {
  for (const t of tokens || []) {
    if (t.type === "heading") {
      out.push({ level: t.depth, text: plain(marked.parseInline(t.text || "") || t.text || "") });
    } else if (t.tokens) {
      headingTokens(t.tokens, out);
    } else if (t.items) {
      for (const item of t.items) headingTokens(item.tokens, out);
    }
  }
  return out;
}

/** Wrap h2-and-below into <section> so each one can fold.
 *
 *  Regex surgery on rendered HTML rather than a custom tokenizer: the HTML at
 *  this point is entirely generated by this file, so the shape is known, and a
 *  regex keeps the section logic readable next to the folding CSS.
 */
/**
 * Wrap h2-and-below into <section> so each one can fold, and drop in the
 * backlinks that point at THAT section.
 *
 * Section-level backlinks are the reason anchors are positional (`sec-1`,
 * `sec-2`): a link to `{{ref:x|#sec-3}}` can be resolved to the section it lands
 * in, so a reader finishing a section immediately sees who else cites that part
 * rather than only which pages cite the whole piece. gwern calls this the
 * in-context backlink, and most backlink systems cannot do it.
 */
export function buildSections(html, headings, backlinksBySection = new Map()) {
  const byId = new Map(headings.map((h) => [h.id, h]));

  const backlinkBlock = (id) => {
    const list = backlinksBySection.get(id);
    if (!list || !list.length) return "";
    return `<div class="sectionback">\n<p class="sectionback__h">本节被这些地方引用</p>\n<ul class="sectionback__list">\n${
      list.map((b) => `<li><a href="${esc(b.fromUrl)}#${esc(id)}">${esc(b.fromTitle)}</a>${
        b.context ? `<span class="sectionback__ctx">${esc(b.context)}</span>` : ""
      }</li>`).join("\n")
    }\n</ul>\n</div>\n`;
  };

  // The rendered HTML is entirely ours, so splitting on headings is safe and
  // keeps the section boundaries and the backlink placement in one pass.
  //
  // Sections NEST: an h3 belongs to the h2 above it, so folding that h2 hides
  // the whole section, subsections included. Emitting them as siblings was the
  // first version, and it meant folding a section left its subsections on
  // screen — which reads as a broken fold, not as a design choice.
  const parts = html.split(/(?=<h[23] id=")/);
  let out = "";
  const open = [];   // ids of the sections currently open, outermost first

  const closeTo = (level) => {
    while (open.length && open[open.length - 1].level >= level) {
      const s = open.pop();
      out += backlinkBlock(s.id) + "</section>";
    }
  };

  for (const part of parts) {
    const m = /^<h([23]) id="([^"]+)"/.exec(part);
    if (!m) {
      out += part;
      continue;
    }
    const level = Number(m[1]);
    const id = m[2];
    closeTo(level);

    const h = byId.get(id);
    const title = h ? h.text : "";
    open.push({ id, level });
    out += `<section class="${level === 2 ? "sec" : "subsec"}" aria-labelledby="${id}">` +
      part.replace(
        new RegExp(`^<h${level} id="${id}"([^>]*)>`),
        `<h${level} id="${id}"$1><a class="anchor" href="#${id}" aria-label="本节链接：${esc(title)}">#</a>`
      );
  }
  closeTo(2);

  return out;
}

/** Fold controls are added by script, not marked up here — a client that cannot
 *  run the script must still see every section open. */
export const SECTION_SCRIPT_MARKER = "<!--fold-->";

/* ══════════════════════════════════════════════════════════════════════ */
/* block extensions                                                      */
/* ══════════════════════════════════════════════════════════════════════ */
/*
 * Five gwern-style block forms, all preprocessed BEFORE marked.
 *
 * Preprocessing rather than a marked extension is deliberate: each of these
 * brackets a region of ORDINARY Markdown, and doing it this way means the
 * body keeps being parsed normally instead of being handed to a tokenizer that
 * has to re-implement everything. The cost is that the delimiters must sit on
 * their own lines at column zero, which is exactly how they are written.
 *
 * Every one of them is emitted as a real HTML block with no script involved,
 * so all five survive JavaScript being switched off.
 */

const ADMONITIONS = {
  note: { name: "附注", glyph: "※" },
  aside: { name: "旁白", glyph: "◇" },
  warn: { name: "注意", glyph: "!" },
  quote: { name: "引文", glyph: "❝" },
  tip: { name: "提示", glyph: "✦" }
};

/**
 * Where one of these blocks ends.
 *
 * Every scanner below must use THIS pattern. They originally each spelled the
 * stop condition out themselves, and the copies drifted: two of them required a
 * space after the marker, so a bare `:::` did not stop the scanner, the
 * columns block was swallowed into the preceding admonition, and the whole
 * thing then failed to render as HTML at all. One constant, one meaning.
 */
/**
 * A line that begins — and therefore terminates — one of these blocks.
 *
 * Loosely anchored on purpose. `+++ 标题` is a block fold just as much as the
 * bracketed `+++[标题]` form, and `:::` stands alone. An earlier version
 * demanded a space after every marker in some scanners and not others, so a
 * bare `:::` failed to end the block above it and the two ran together. One
 * pattern, used by every scanner.
 */
const BLOCK_START = /^(?:!!!|\+\+\+|---|>>>|:::)(?:\s|$)/;
const isBlockStart = (line) => BLOCK_START.test(line) || /^#{1,6}\s/.test(line);

/** Gather the body of a block that starts at `i`. */
function gatherBody(lines, i) {
  const body = [];
  let j = i + 1;
  while (j < lines.length && !isBlockStart(lines[j])) {
    body.push(lines[j]);
    j++;
  }
  return { body, end: j - 1 };
}

/**
 * The `!` family: margin notes and admonitions.
 *
 * `!!!` and `!!!note` are the SAME first token, and they were originally handled
 * by two different passes in two different modules. The margin-note pass ran
 * first and quietly consumed every admonition, so admonitions never rendered —
 * they appeared as margin-note text, and nothing failed. They are scanned
 * together here so the split is visible and cannot regress.
 *
 *   !!! 文字          margin note — a skimmable summary of what follows
 *   !!! note 标题     admonition, with a type and an optional title
 */
function replaceBangs(src, notes) {
  const lines = src.split(/\r?\n/);
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    const m = /^!!!\s*([a-zA-Z]+)?\s*(.*)$/.exec(lines[i]);
    if (!m) { out.push(lines[i]); continue; }

    const type = (m[1] || "").toLowerCase();
    const rest = (m[2] || "").trim();

    if (type && Object.prototype.hasOwnProperty.call(ADMONITIONS, type)) {
      const conf = ADMONITIONS[type];
      const { body, end } = gatherBody(lines, i);
      i = end;
      // blank lines around the div, or marked treats it as inline HTML inside
      // an enclosing paragraph and escapes the whole thing
      out.push("", `<div class="admon admon--${esc(type)}" role="note">`,
        `<p class="admon__title"><span class="admon__glyph" aria-hidden="true">${conf.glyph}</span>${esc(rest || conf.name)}</p>`,
        "",
        body.join("\n").trim(),
        "",
        "</div>", "");
      continue;
    }

    // anything else is a margin note; the type word, if any, is its text
    const text = (m[1] ? m[1] + " " : "") + rest;
    notes.push(text.trim());
    out.push("", `<div class="marginnote">${esc(text.trim())}</div>`, "");
  }
  return { text: out.join("\n"), notes };
}

/**
 * `+++[标题]` or `+++ 标题` — a foldable block.
 *
 * The bracketed form is the explicit one; the bare form takes the rest of the
 * line as its label. Both are BLOCK folds, because a fold with no label and no
 * body would be indistinguishable from a paragraph — if you want a one-line
 * fold, write the line.
 */
function replaceFolds(src) {
  const lines = src.split(/\r?\n/);
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    const m = /^\+\+\+(?:\[([^\]]*)\]|)\s*(.*)$/.exec(lines[i]);
    if (!m) { out.push(lines[i]); continue; }

    const label = (m[1] !== undefined && m[1] !== null ? m[1] : (m[2] || "")).trim();
    const { body, end } = gatherBody(lines, i);
    i = end;

    out.push("", `<div class="fold">`,
      `<p class="fold__label"><span class="fold__text">${esc(label || "展开")}</span></p>`,
      "",
      body.join("\n").trim(),
      "",
      "</div>", "");
  }
  return out.join("\n");
}

/** `>>> 引文 — 出处` — an epigraph in the serif, indented, no container. */
function replaceEpigraphs(src) {
  return src.replace(
    /^>>>\s*([\s\S]*?)(?:\n\n|$)/gm,
    (_, block) => {
      const text = block.trim();
      // an em dash or "--" on the last line carries the attribution
      const m = /^(.*?)\s*(?:——|--|—)\s*(.+)$/s.exec(text);
      const body = m ? m[1].trim() : text;
      const by = m ? m[2].trim() : "";
      return `<div class="epigraph">\n\n> ${body.replace(/\n/g, "\n> ")}\n\n${
        by ? `<p class="epigraph__by">${esc(by)}</p>` : ""
      }\n\n</div>\n\n`;
    }
  );
}

/** `::: columns` … `:::` — a list that goes multi-column on wide screens. */
function replaceColumns(src) {
  return src.replace(
    /^:::[ \t]*columns[^\n]*\n([\s\S]*?)\n:::[ \t]*$/gm,
    (_, inner) => `\n\n<div class="columns">\n\n${inner.trim()}\n\n</div>\n\n`
  );
}

/**
 * Keyed citations: `[^key]` in the text, `[^key]: reference` at the end.
 *
 * gwern typesets references as subscripts rather than bracketed numbers because
 * they interrupt a sentence far less. The definition lines are collected here so
 * the page can emit one compact reference list; the in-text marker becomes a
 * superscript link to its entry.
 *
 * Note the deliberate distinction from `^[text]`, which is an inline footnote —
 * bracket-caret is a citation, caret-bracket is a note.
 */
function replaceCitations(src) {
  const defs = new Map();
  const order = [];

  // pull the definitions out first so they never render as paragraphs
  let text = src.replace(/^\[\^([^\]]+)\]:[ \t]*(.+)$/gm, (_, key, body) => {
    const k = key.trim();
    if (!defs.has(k)) { defs.set(k, body.trim()); order.push(k); }
    return "";
  });

  const used = [];
  text = text.replace(/\[\^([^\]]+)\]/g, (whole, key) => {
    const k = key.trim();
    if (!defs.has(k)) return whole;      // leave it alone; the build reports it
    let n = used.indexOf(k);
    if (n < 0) { used.push(k); n = used.length - 1; }
    return `<sup class="citeref"><a href="#cite-${esc(slugify(k) || n + 1)}">[${n + 1}]</a></sup>`;
  });

  const list = used.length
    ? `\n\n<section class="references" aria-labelledby="refs-h">\n\n` +
      `<h2 id="refs-h" class="references__h">参考</h2>\n\n` +
      `<ol class="references__list">\n` +
      used.map((k) => `<li id="cite-${esc(slugify(k) || "")}">${esc(defs.get(k))}</li>`).join("\n") +
      `\n</ol>\n\n</section>\n\n`
    : "";

  return { text: text + list, citations: used, missing: [...defs.keys()].filter((k) => !used.includes(k)) };
}

/* ══════════════════════════════════════════════════════════════════════ */
/* renderer                                                              */
/* ══════════════════════════════════════════════════════════════════════ */

function makeRenderer() {
  const renderer = new marked.Renderer();

  renderer.heading = function (token) {
    const text = this.parser.parseInline(token.tokens);
    // ids are assigned after all headings are known; see renderBody()
    return `<h${token.depth} data-h="${esc(plain(token.text || ""))}">${text}</h${token.depth}>\n`;
  };

  renderer.link = function (token) {
    const href = token.href || "";
    const external = /^https?:/i.test(href);
    const cls = external ? "ext" : "int";
    return `<a class="${cls}" href="${esc(href)}"${
      external ? ' target="_blank" rel="noopener noreferrer"' : ""
    }${token.title ? ` title="${esc(token.title)}"` : ""}>${this.parser.parseInline(token.tokens)}</a>`;
  };

  renderer.code = function (token) {
    // A plain-text site has no syntax highlighter, but indented verse must keep
    // its leading whitespace — so a code block is rendered as preserved text
    // rather than being silently reflowed.
    return `<pre class="verbatim">${esc(token.text)}</pre>\n`;
  };

  renderer.blockquote = function (token) {
    return `<blockquote>${this.parser.parse(token.tokens)}</blockquote>\n`;
  };

  renderer.hr = () => `<hr class="divider">\n`;

  return renderer;
}

/* ══════════════════════════════════════════════════════════════════════ */
/* body                                                                  */
/* ══════════════════════════════════════════════════════════════════════ */

/**
 * Render one article body.
 *
 * Order matters: footnotes and margin notes are expanded first (their bodies
 * are Markdown), then refs are pulled out as placeholders so marked never sees
 * a half-formed link, then Markdown runs, then refs are restored and headings
 * get their final ids.
 */
export function renderBody(article, { resolve, sectionBacklinks = new Map() } = {}) {
  const notes = [];
  let src = article.body;

  // Block extensions run before refs are pulled out, so a `{{ref:}}` inside an
  // admonition or a fold is still recognised as a link.
  src = replaceColumns(src);
  const bangs = replaceBangs(src, []);
  src = bangs.text;
  src = replaceFolds(src);
  src = replaceEpigraphs(src);

  // Inline footnotes come after the block scanners: their bodies are Markdown
  // and may contain markers, and running them last keeps the two `!` forms from
  // being confused for each other.
  src = replaceFootnotes(src, notes);

  const cites = replaceCitations(src);
  src = cites.text;

  const { text, links } = extractRefs(src, article.slug);

  let html = marked.parse(text, {
    renderer: makeRenderer(),
    gfm: true,
    breaks: false
  });

  html = restoreRefs(html, links, resolve);
  html = linkIcons(html);

  // position the headings now that the document is whole
  const collected = headingTokens(marked.lexer(text));
  const headings = [];
  let n = 0;
  html = html.replace(/<h([1-6]) data-h="[^"]*">/g, (_, level) => {
    const src2 = collected[n];
    n += 1;
    const depth = Number(level);
    const id = `sec-${n}`;
    headings.push({ level: depth, id, text: src2 ? src2.text : "" });
    return `<h${depth} id="${id}">`;
  });

  const sectioned = buildSections(html, headings, sectionBacklinks);

  return {
    html: sectioned,
    headings: headings.filter((h) => h.level === 2),
    allHeadings: headings,
    notes,
    citations: cites.citations,
    unusedCitations: cites.missing,
    links: links.map((l) => l.target)
  };
}

/**
 * Tag external links by what they point at.
 *
 * gwern.net does this with several hundred hand-tuned regexes and a folder of
 * icons; this is the abbreviated version — four categories, drawn as an inline
 * SVG so nothing is requested, and applied by attribute selector in CSS rather
 * than by rewriting every link.
 *
 * The icon is `aria-hidden` and the information is also carried in the link's
 * `title`, so it is decoration for sighted readers rather than the only signal.
 */
export function linkIcons(html) {
  return html.replace(/<a class="ext"([^>]*)>/g, (whole, attrs) => {
    const href = /href="([^"]*)"/.exec(attrs);
    if (!href) return whole;
    const url = href[1];
    let kind = "web";
    if (/\.pdf(?:$|\?)/i.test(url)) kind = "pdf";
    else if (/^https?:\/\/(?:en\.)?wikipedia\.org\//i.test(url)) kind = "wikipedia";
    else if (/^https?:\/\/(?:dx\.)?doi\.org\//i.test(url)) kind = "doi";
    else if (/^https?:\/\/(?:arxiv\.org|www\.arxiv\.org)\//i.test(url)) kind = "arxiv";
    return `<a class="ext ext--${kind}"${attrs}>`;
  });
}

/* ══════════════════════════════════════════════════════════════════════ */
/* text for search / preview                                             */
/* ══════════════════════════════════════════════════════════════════════ */

/** Plain text of a rendered body, for the search index. Notes and refs are
 *  included: a note often carries the detail someone is searching for. */
export const searchText = (html) => plain(html).slice(0, 20000);

/** A short excerpt around the first occurrence of `needle`, for previews. */
export function excerpt(html, needle, width = 260) {
  const text = plain(html);
  if (!needle) return text.slice(0, width) + (text.length > width ? "…" : "");
  const i = text.toLowerCase().indexOf(String(needle).toLowerCase());
  if (i < 0) return text.slice(0, width) + (text.length > width ? "…" : "");
  const start = Math.max(0, i - 60);
  return (start > 0 ? "…" : "") + text.slice(start, start + width) + "…";
}
