/**
 * render.mjs — Markdown to HTML for this site.
 *
 * Three things here are site-specific rather than generic Markdown:
 *
 *  1. Stable heading anchors. A Chinese heading slugifies to nothing usable, so
 *     ids are positional (`sec-1`, `sec-2`) and never derived from the text —
 *     which also means editing a heading's wording cannot break a link
 *     someone saved.
 *  2. Section wrappers with a disclosure control, which is the whole of gwern's
 *     "semantic zoom" at the block level: a long piece can be read as headings
 *     alone, then expanded section by section.
 *  3. Footnote/sidenote and `{{ref:}}` handling, both preprocessed BEFORE
 *     marked so their bodies are themselves parsed as Markdown.
 */

import { marked } from "marked";
import { esc, plain } from "./lib.mjs";
import { replaceFootnotes, replaceMarginNotes, extractRefs, restoreRefs } from "./content.mjs";

/* ══════════════════════════════════════════════════════════════════════ */
/* headings & sections                                                   */
/* ══════════════════════════════════════════════════════════════════════ */

/** Collect every heading's level, text and positional id. */
function headingTokens(tokens, out = []) {
  for (const t of tokens || []) {
    if (t.type === "heading") {
      out.push({ level: t.depth, text: plain(marked.parseInline(t.text || "") || t.text || "") });
    } else if (t.tokens) {
      headingTokens(t.tokens, out);
    } else if (t.items) {
      for (const item of t.items) headingTokens(item.tokens, out);
    }
  }
  return out;
}

/** Wrap h2-and-below into <section> so each one can fold.
 *
 *  Regex surgery on rendered HTML rather than a custom tokenizer: the HTML at
 *  this point is entirely generated by this file, so the shape is known, and a
 *  regex keeps the section logic readable next to the folding CSS.
 */
export function buildSections(html, headings) {
  const byId = new Map(headings.map((h) => [h.id, h]));

  // open a section at each h2/h3 and close the previous one
  let out = html.replace(
    /<h([23]) id="([^"]+)"([^>]*)>/g,
    (_, level, id, rest) => {
      const h = byId.get(id);
      const title = h ? h.text : "";
      const open = level === "2"
        ? `<section class="sec" aria-labelledby="${id}">`
        : `<section class="subsec" aria-labelledby="${id}">`;
      return `</section>${open}<h${level} id="${id}"${rest}>` +
        `<a class="anchor" href="#${id}" aria-label="本节链接：${esc(title)}">#</a>`;
    }
  );

  // the first section opens before the first heading, so drop the leading close
  out = out.replace(/^<\/section>/, "");
  // and close the final one
  out += "</section>";

  return out;
}

/** Fold controls are added by script, not marked up here — a client that cannot
 *  run the script must still see every section open. */
export const SECTION_SCRIPT_MARKER = "<!--fold-->";

/* ══════════════════════════════════════════════════════════════════════ */
/* renderer                                                              */
/* ══════════════════════════════════════════════════════════════════════ */

function makeRenderer() {
  const renderer = new marked.Renderer();

  renderer.heading = function (token) {
    const text = this.parser.parseInline(token.tokens);
    // ids are assigned after all headings are known; see renderBody()
    return `<h${token.depth} data-h="${esc(plain(token.text || ""))}">${text}</h${token.depth}>\n`;
  };

  renderer.link = function (token) {
    const href = token.href || "";
    const external = /^https?:/i.test(href);
    const cls = external ? "ext" : "int";
    return `<a class="${cls}" href="${esc(href)}"${
      external ? ' target="_blank" rel="noopener noreferrer"' : ""
    }${token.title ? ` title="${esc(token.title)}"` : ""}>${this.parser.parseInline(token.tokens)}</a>`;
  };

  renderer.code = function (token) {
    // A plain-text site has no syntax highlighter, but indented verse must keep
    // its leading whitespace — so a code block is rendered as preserved text
    // rather than being silently reflowed.
    return `<pre class="verbatim">${esc(token.text)}</pre>\n`;
  };

  renderer.blockquote = function (token) {
    return `<blockquote>${this.parser.parse(token.tokens)}</blockquote>\n`;
  };

  renderer.hr = () => `<hr class="divider">\n`;

  return renderer;
}

/* ══════════════════════════════════════════════════════════════════════ */
/* body                                                                  */
/* ══════════════════════════════════════════════════════════════════════ */

/**
 * Render one article body.
 *
 * Order matters: footnotes and margin notes are expanded first (their bodies
 * are Markdown), then refs are pulled out as placeholders so marked never sees
 * a half-formed link, then Markdown runs, then refs are restored and headings
 * get their final ids.
 */
export function renderBody(article, { resolve }) {
  const notes = [];
  let src = replaceMarginNotes(article.body);
  src = replaceFootnotes(src, notes);
  const { text, links } = extractRefs(src, article.slug);

  let html = marked.parse(text, {
    renderer: makeRenderer(),
    gfm: true,
    breaks: false
  });

  html = restoreRefs(html, links, resolve);

  // position the headings now that the document is whole
  const collected = headingTokens(marked.lexer(text));
  const headings = [];
  let n = 0;
  html = html.replace(/<h([1-6]) data-h="[^"]*">/g, (_, level) => {
    const src2 = collected[n];
    n += 1;
    const depth = Number(level);
    const id = `sec-${n}`;
    headings.push({ level: depth, id, text: src2 ? src2.text : "" });
    return `<h${depth} id="${id}">`;
  });

  const sectioned = buildSections(html, headings);

  return {
    html: sectioned,
    headings: headings.filter((h) => h.level === 2),
    allHeadings: headings,
    notes,
    links: links.map((l) => l.target)
  };
}

/* ══════════════════════════════════════════════════════════════════════ */
/* text for search / preview                                             */
/* ══════════════════════════════════════════════════════════════════════ */

/** Plain text of a rendered body, for the search index. Notes and refs are
 *  included: a note often carries the detail someone is searching for. */
export const searchText = (html) => plain(html).slice(0, 20000);

/** A short excerpt around the first occurrence of `needle`, for previews. */
export function excerpt(html, needle, width = 260) {
  const text = plain(html);
  if (!needle) return text.slice(0, width) + (text.length > width ? "…" : "");
  const i = text.toLowerCase().indexOf(String(needle).toLowerCase());
  if (i < 0) return text.slice(0, width) + (text.length > width ? "…" : "");
  const start = Math.max(0, i - 60);
  return (start > 0 ? "…" : "") + text.slice(start, start + width) + "…";
}
